name: Alerta Discord
on: [push]

jobs:
  envio-alerta:
    runs-on: ubuntu-latest
    steps:
      - name: Mandar Mensagem
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: " Alerta da Semana 6: Vinicius, seu pipeline de monitoramento está ativo!"
